In [309]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
plt.style.use('bmh')

In [310]:
players = pd.read_csv(r"C:\Users\kyrie\ironhack\Excel_CSV_file\nba\games_details.csv")
players.head(20)

C:\Users\kyrie\AppData\Local\Temp\ipykernel_10340\47981702.py:1: DtypeWarning: Columns (6) have mixed types. Specify dtype option on import or set low_memory=False.
  players = pd.read_csv(r"C:\Users\kyrie\ironhack\Excel_CSV_file\nba\games_details.csv")

,GAME_ID,TEAM_ID,TEAM_ABBREVIATION,TEAM_CITY,PLAYER_ID,PLAYER_NAME,NICKNAME,START_POSITION,COMMENT,MIN,...,OREB,DREB,REB,AST,STL,BLK,TO,PF,PTS,PLUS_MINUS
0,22101005,1610612750,MIN,Minnesota,1630162,Anthony Edwards,Anthony,F,NaN,36:22,...,0.0,8.0,8.0,5.0,3.0,1.0,1.0,1.0,15.0,5.0
1,22101005,1610612750,MIN,Minnesota,1630183,Jaden McDaniels,Jaden,F,NaN,23:54,...,2.0,4.0,6.0,0.0,0.0,2.0,2.0,6.0,14.0,10.0
2,22101005,1610612750,MIN,Minnesota,1626157,Karl-Anthony Towns,Karl-Anthony,C,NaN,25:17,...,1.0,9.0,10.0,0.0,0.0,0.0,3.0,4.0,15.0,14.0
3,22101005,1610612750,MIN,Minnesota,1627736,Malik Beasley,Malik,G,NaN,30:52,...,0.0,3.0,3.0,1.0,1.0,0.0,1.0,4.0,12.0,20.0
4,22101005,1610612750,MIN,Minnesota,1626156,D'Angelo Russell,D'Angelo,G,NaN,33:46,...,0.0,6.0,6.0,9.0,1.0,0.0,5.0,0.0,14.0,17.0
5,22101005,1610612750,MIN,Minnesota,1629675,Naz Reid,Naz,NaN,NaN,23:56,...,3.0,7.0,10.0,1.0,3.0,2.0,1.0,1.0,11.0,-7.0
6,22101005,1610612750,MIN,Minnesota,1629162,Jordan McLaughlin,Jordan,NaN,NaN,21:00,...,0.0,1.0,1.0,3.0,3.0,0.0,0.0,1.0,5.0,-10.0
7,22101005,1610612750,MIN,Minnesota,1629669,Jaylen Nowell,Jaylen,NaN,NaN,21:35,...,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,16.0,-5.0
8,22101005,1610612750,MIN,Minnesota,1627752,Taurean Prince,Taurean,NaN,NaN,22:53,...,0.0,2.0,2.0,1.0,1.0,0.0,1.0,2.0,11.0,1.0
9,22101005,1610612750,MIN,Minnesota,1629006,Josh Okogie,Josh,NaN,NaN,0:25,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
10,22101005,1610612750,MIN,Minnesota,1630195,Leandro Bolmaro,Leandro,NaN,DNP - Coach's Decision,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
11,22101005,1610612750,MIN,Minnesota,1630233,Nathan Knight,Nathan,NaN,DNP - Coach's Decision,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
12,22101005,1610612750,MIN,Minnesota,1627774,Jake Layman,Jake,NaN,DNP - Coach's Decision,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
13,22101005,1610612748,MIA,Miami,1629130,Duncan Robinson,Duncan,F,NaN,16:31,...,0.0,0.0,0.0,4.0,0.0,0.0,0.0,3.0,3.0,-21.0
14,22101005,1610612748,MIA,Miami,200782,P.J. Tucker,P.J.,F,NaN,23:17,...,4.0,3.0,7.0,0.0,0.0,0.0,3.0,4.0,6.0,-25.0
15,22101005,1610612748,MIA,Miami,1628389,Bam Adebayo,Bam,C,NaN,33:28,...,2.0,10.0,12.0,4.0,3.0,0.0,4.0,2.0,19.0,0.0
16,22101005,1610612748,MIA,Miami,1629216,Gabe Vincent,Gabe,G,NaN,25:23,...,0.0,1.0,1.0,3.0,2.0,0.0,1.0,2.0,2.0,-22.0
17,22101005,1610612748,MIA,Miami,200768,Kyle Lowry,Kyle,G,NaN,37:24,...,2.0,5.0,7.0,7.0,0.0,0.0,3.0,2.0,14.0,-7.0
18,22101005,1610612748,MIA,Miami,1629639,Tyler Herro,Tyler,NaN,NaN,36:30,...,0.0,7.0,7.0,2.0,2.0,0.0,1.0,1.0,30.0,11.0
19,22101005,1610612748,MIA,Miami,1629622,Max Strus,Max,NaN,NaN,31:18,...,1.0,6.0,7.0,2.0,0.0,0.0,1.0,5.0,19.0,14.0

In [311]:
players.shape

(645953, 29)

In [312]:
players_sample = players.head(1000)
players_sample.to_csv(r"C:\Users\kyrie\ironhack\final_project\players_sample.csv")

In [313]:
players.isna().sum().sort_values(ascending=False)

NICKNAME             615591
COMMENT              540351
START_POSITION       398738
PLUS_MINUS           129264
FTM                  105603
PTS                  105603
PF                   105603
TO                   105603
BLK                  105603
STL                  105603
AST                  105603
REB                  105603
DREB                 105603
OREB                 105603
FT_PCT               105603
FTA                  105603
FG3A                 105603
FG3_PCT              105603
FG3M                 105603
FG_PCT               105603
FGA                  105603
FGM                  105603
MIN                  105603
TEAM_ID                   0
PLAYER_NAME               0
PLAYER_ID                 0
TEAM_CITY                 0
TEAM_ABBREVIATION         0
GAME_ID                   0
dtype: int64

In [314]:
players.TEAM_CITY.unique()

array(['Minnesota', 'Miami', 'Cleveland', 'Chicago', 'Indiana',
       'San Antonio', 'Milwaukee', 'Golden State', 'Toronto', 'Denver',
       'Sacramento', 'Utah', 'Washington', 'Portland', 'Orlando', 'LA',
       'Atlanta', 'Detroit', 'Boston', 'Dallas', 'Houston', 'New York',
       'Memphis', 'Charlotte', 'New Orleans', 'Phoenix', 'Los Angeles',
       'Brooklyn', 'Philadelphia', 'Oklahoma City', 'New Jersey',
       'Seattle', 'New Orleans/Oklahoma City'], dtype=object)

In [315]:
milwaukee = players.loc[players.TEAM_CITY == "Milwaukee"]

In [316]:
milwaukee.PLAYER_NAME.value_counts()

Giannis Antetokounmpo    780
Ersan Ilyasova           760
Khris Middleton          739
Dan Gadzuric             577
John Henson              539
                        ...
Brandon Williams           1
Charlie Westbrook          1
Ha Ha                      1
TJ Cummings                1
Jon Horford                1
Name: PLAYER_NAME, Length: 239, dtype: int64

In [317]:
milwaukee.PLAYER_NAME.unique()

array(['Khris Middleton', 'Giannis Antetokounmpo', 'Bobby Portis',
       'Grayson Allen', 'Jrue Holiday', 'Jevon Carter', 'Wesley Matthews',
       'Serge Ibaka', 'Jordan Nwora', "DeAndre' Bembry",
       'Sandro Mamukelashvili', 'Thanasis Antetokounmpo',
       'Lindell Wigginton', 'Greg Monroe', 'Pat Connaughton',
       'Donte DiVincenzo', 'Rodney Hood', 'Semi Ojeleye', 'George Hill',
       'Langston Galloway', 'Luke Kornet', 'Javonte Smart', 'Jeff Dowtin',
       'DeMarcus Cousins', 'Javin DeLaurier', 'Georgios Kalaitzakis',
       'Justin Robinson', 'Brook Lopez', 'Tremont Waters',
       'Elijah Bryant', "Johnny O'Bryant III", 'P.J. Tucker',
       'Jeff Teague', 'Mamadi Diakite', 'Bryn Forbes', 'Justin Jackson',
       'Sam Merrill', 'Axel Toupane', 'Rodions Kurucs', 'D.J. Augustin',
       'D.J. Wilson', 'Torrey Craig', 'Jaylen Adams', 'Nik Stauskas',
       'Treveon Graham', 'E.J. Montgomery', 'Justin Patton',
       'Eric Bledsoe', 'Marvin Williams', 'Kyle Korver', 'Sterling Brown',
       'Ersan Ilyasova', 'Robin Lopez', 'Frank Mason', 'Dragan Bender',
       'Richard Jefferson', 'Luc Mbah a Moute', 'Dan Gadzuric',
       'Charlie Bell', 'Ramon Sessions', 'Francisco Elson',
       'Charlie Villanueva', 'Joe Alexander', 'Luke Ridnour',
       'Malik Allen', 'Keith Bogans', 'Damon Jones', 'Eddie Gill',
       'Tyronn Lue', 'Andrew Bogut', 'Michael Redd', 'Austin Croshere',
       'Matt Freije', 'Ron Howard', 'Kevin Kruger', 'Adrian Griffin',
       'TJ Cummings', 'Desmond Mason', 'Bobby Simmons', 'Awvee Storey',
       'Jake Voskuhl', 'Michael Ruffin', 'Royal Ivey', 'Mo Williams',
       'Yi Jianlian', 'David Noel', 'Ruben Patterson', 'Jared Reiner',
       'Earl Boykins', 'Lynn Greer', 'Damir Markota', 'Brian Skinner',
       'Julius Hodge', 'Steve Blake', 'Chris McCray', 'Ha Ha',
       'Mike Harris', 'Jamaal Magloire', 'T.J. Ford', 'Toni Kukoc',
       'Joe Smith', 'Jiri Welsch', 'Ervin Johnson', 'Jermaine Jackson',
       'Reece Gaines', 'Josh Davis', 'Tommy Smith', 'Andre Barrett',
       'Brandon Hunter', 'Erick Strickland', 'Marcus Fizer',
       'Anthony Goldwire', 'Zaza Pachulia', 'Daniel Santiago',
       'Calvin Booth', 'Mike James', 'Keith Van Horn', 'Zendon Hamilton',
       'Kendall Gill', 'Eddie House', 'Marcus Haislip',
       'Brandon Williams', 'Juaquin Hawkins', 'Jelani McCoy',
       'Brevin Knight', 'Tim Thomas', 'Joel Przybilla', 'Dan Langhi',
       'Antonio Meeking', 'Tobias Harris', 'Jon Leuer', 'Ekpe Udoh',
       'Shaun Livingston', 'Brandon Jennings', 'Larry Sanders',
       'Mike Dunleavy', 'Beno Udrih', 'Jon Brockman', 'Carlos Delfino',
       'Monta Ellis', 'Drew Gooden', 'Stephen Jackson',
       'Darington Hobson', 'John Salmons', 'Keyon Dooling',
       'Corey Maggette', 'Chris Douglas-Roberts', 'Earl Barron',
       'Garrett Temple', 'Chris Kramer', 'Kurt Thomas',
       'Jerry Stackhouse', 'Primoz Brezec', 'Darnell Jackson',
       'Jodie Meeks', 'Hakim Warrick', 'Roko Ukic', 'Cameron Reynolds',
       'Rayjon Tucker', 'Luke Maye', 'Malcolm Brogdon', 'Tim Frazier',
       'Nikola Mirotic', 'Tony Snell', 'Bonzie Colson', 'Pau Gasol',
       'Christian Wood', 'Trevon Duval', 'Isaiah Canaan', 'Thon Maker',
       'Jason Smith', 'Jaylen Morris', 'Matthew Dellavedova',
       'John Henson', 'Tyler Zeller', 'Shabazz Muhammad', 'Jabari Parker',
       'Jason Terry', 'Xavier Munford', 'Marshall Plumlee',
       'Sean Kilpatrick', 'Rashad Vaughn', 'DeAndre Liggins',
       'Joel Bolomboy', 'Gary Payton II', 'Mirza Teletovic',
       'Joel Anthony', 'Gerald Green', 'Brandon Rush', 'Kendall Marshall',
       'James Young', 'Michael Beasley', 'Spencer Hawes',
       'Terrence Jones', 'Roy Hibbert', 'Steve Novak', 'Miles Plumlee',
       'Orlando Johnson', "JJ O'Brien", 'Jaleel Roberts',
       'Michael Carter-Williams', 'Tyler Ennis', 'Greivis Vasquez',
       'Damien Inglis', 'Jerryd Bayless', 'Jared Cunningham', 'O.J. Mayo',
       'Chris Copeland', 'Marcus Landry', 'Josh Powell',
       'Jorge Gutierrez', 'Charlie Westbrook', 'Jon Horford',
       'Jared Dudley', 'Chris Johnson', 'Brandon Knight', 'Kenyon Martin',
       'Nate Wolters', 'Micheal Eric', 'Elijah Millsap', 'Chris Wright',
       'Jeff Adrien', 'Miroslav Raduljica', 'DJ Stephens',
       'Tony Mitchell', 'Caron Butler', 'Gary Neal', 'Stephen Graham',
       'Trey McKinney-Jones', 'Olek Czyz', 'JJ Redick', 'Ish Smith',
       'Gustavo Ayon', 'Samuel Dalembert', 'Marquis Daniels',
       'Doron Lamb', 'Alando Tucker', 'Mustapha Farrakhan',
       'Orien Greene'], dtype=object)

In [318]:
giannis = milwaukee.loc[milwaukee.PLAYER_NAME == "Giannis Antetokounmpo"]
giannis

,GAME_ID,TEAM_ID,TEAM_ABBREVIATION,TEAM_CITY,PLAYER_ID,PLAYER_NAME,NICKNAME,START_POSITION,COMMENT,MIN,...,OREB,DREB,REB,AST,STL,BLK,TO,PF,PTS,PLUS_MINUS
72,22101008,1610612749,MIL,Milwaukee,203507,Giannis Antetokounmpo,Giannis,F,NaN,34:01,...,1.0,7.0,8.0,3.0,0.0,1.0,1.0,2.0,31.0,-26.0
555,22100984,1610612749,MIL,Milwaukee,203507,Giannis Antetokounmpo,Giannis,F,NaN,37:03,...,3.0,9.0,12.0,5.0,1.0,0.0,2.0,4.0,43.0,3.0
859,22100979,1610612749,MIL,Milwaukee,203507,Giannis Antetokounmpo,Giannis,F,NaN,27:46,...,1.0,6.0,7.0,7.0,3.0,1.0,1.0,3.0,39.0,18.0
1144,22100961,1610612749,MIL,Milwaukee,203507,Giannis Antetokounmpo,Giannis,F,NaN,31:13,...,3.0,10.0,13.0,6.0,1.0,3.0,3.0,6.0,19.0,-8.0
1556,22100949,1610612749,MIL,Milwaukee,203507,Giannis Antetokounmpo,Giannis,F,NaN,38:48,...,4.0,12.0,16.0,5.0,2.0,1.0,4.0,4.0,34.0,15.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
607784,11300086,1610612749,MIL,Milwaukee,203507,Giannis Antetokounmpo,NaN,NaN,NaN,27,...,1.0,5.0,6.0,1.0,2.0,2.0,1.0,4.0,6.0,NaN
608563,11300053,1610612749,MIL,Milwaukee,203507,Giannis Antetokounmpo,NaN,NaN,NaN,19,...,1.0,2.0,3.0,0.0,1.0,0.0,0.0,1.0,8.0,NaN
608914,11300042,1610612749,MIL,Milwaukee,203507,Giannis Antetokounmpo,NaN,NaN,NaN,14,...,1.0,4.0,5.0,2.0,0.0,1.0,0.0,0.0,2.0,NaN
609195,11300028,1610612749,MIL,Milwaukee,203507,Giannis Antetokounmpo,NaN,NaN,NaN,28,...,0.0,7.0,7.0,0.0,1.0,4.0,7.0,5.0,4.0,NaN
609482,11300016,1610612749,MIL,Milwaukee,203507,Giannis Antetokounmpo,NaN,NaN,NaN,29,...,0.0,4.0,4.0,2.0,2.0,3.0,5.0,5.0,14.0,NaN

In [319]:
giannis.isna().sum().sort_values(ascending=False)

COMMENT              752
NICKNAME             698
START_POSITION       103
PLUS_MINUS            34
FTM                   28
PTS                   28
PF                    28
TO                    28
BLK                   28
STL                   28
AST                   28
REB                   28
DREB                  28
OREB                  28
FT_PCT                28
FTA                   28
FG3A                  28
FG3_PCT               28
FG3M                  28
FG_PCT                28
FGA                   28
FGM                   28
MIN                   28
TEAM_ID                0
PLAYER_NAME            0
PLAYER_ID              0
TEAM_CITY              0
TEAM_ABBREVIATION      0
GAME_ID                0
dtype: int64

In [320]:
giannis = giannis.drop(['COMMENT','NICKNAME','TEAM_ABBREVIATION'], axis=1)

In [321]:
giannis.MIN.unique()

array(['34:01', '37:03', '27:46', '31:13', '38:48', '34:24', '28:09',
       '36:13', '39:07', '36:07', '29:47', '35:19', '30:48', '24:37',
       '37:58', '30:47', '34:06', '29:20', '36:40', '31:14', '36:59',
       '35:29', '29:58', '35:00', '36:44', '26:47', '35:36', '32:12',
       '30:55', '29:34', '33:35', '32:26', '32:36', '27:21', nan, '37:41',
       '32:40', '30:06', '31:10', '23:44', '30:22', '35:44', '36:17',
       '33:45', '37:39', '36:12', '39:11', '30:30', '26:48', '34:56',
       '34:04', '34:54', '36:15', '22:48', '30:57', '25:06', '20:59',
       '17:26', '42:27', '40:35', '42:49', '37:40', '40:08', '35:20',
       '24:04', '40:49', '29:06', '41:01', '50:08', '41:10', '41:49',
       '38:21', '42:60', '35:15', '36:09', '32:35', '30:53', '45:27',
       '33:39', '35:04', '32:15', '28:34', '29:40', '37:26', '35:41',
       '0:46', '37:28', '35:21', '23:43', '35:27', '35:11', '29:12',
       '24:52', '33:05', '35:30', '33:44', '27:17', '32:53', '38:01',
       '24:14', '31:59', '26:42', '36:24', '42:50', '35:43', '36:11',
       '29:23', '36:14', '32:59', '39:55', '37:52', '29:08', '33:29',
       '35:45', '37:05', '37:17', '35:56', '38:52', '37:55', '34:19',
       '31:50', '33:20', '30:37', '25:47', '39:24', '38:51', '37:47',
       '36:22', '35:03', '39:48', '30:11', '33:28', '32:41', '28:28',
       '36:04', '27:12', '24:43', '11:29', '35:39', '36:36', '28:22',
       '33:36', '30:36', '31:36', '34:27', '10:09', '33:25', '15:47',
       '32:07', '23:07', '21:37', '35:31', '28:15', '30:45', '34:55',
       '38:00', '24:51', '31:47', '33:34', '33:01', '30:34', '31:54',
       '32:13', '31:00', '25:24', '21:26', '28:30', '28:18', '32:05',
       '33:50', '28:58', '31:29', '27:22', '30:19', '26:02', '32:20',
       '34:23', '23:59', '26:46', '34:43', '26:20', '27:55', '21:58',
       '19:37', '32:03', '35:12', '38:29', '27:13', '35:48', '30:09',
       '28:24', '35:50', '36:26', '36:25', '30:16', '34:38', '36:38',
       '28:10', '23:00', '20:38', '40:32', '39:15', '34:12', '44:41',
       '34:47', '37:16', '31:07', '34:28', '39:04', '31:02', '34:18',
       '31:55', '27:59', '29:51', '23:28', '24:35', '34:58', '29:56',
       '31:56', '26:03', '29:48', '33:00', '31:57', '32:29', '24:19',
       '32:45', '38:02', '34:50', '30:42', '31:43', '32:42', '34:51',
       '34:40', '37:53', '35:46', '32:25', '21:34', '30:52', '36:32',
       '35:22', '39:38', '19:24', '26:22', '34:41', '33:37', '33:07',
       '31:11', '37:30', '37:02', '33:57', '26:15', '41:50', '38:49',
       '36:28', '29:38', '39:29', '31:37', '34:30', '41:07', '26:25',
       '37:04', '30:05', '19:23', '23:29', '37:21', '36:55', '34:46',
       '25:27', '26:39', '22:29', '41:34', '41:23', '41:27', '40:26',
       '43:01', '44:58', '22:00', '32:49', '42:31', '39:32', '16:40',
       '38:36', '40:27', '35:14', '37:44', '41:52', '43:22', '29:57',
       '39:17', '39:47', '45:22', '39:01', '34:16', '37:54', '40:05',
       '34:39', '27:48', '35:33', '34:36', '32:54', '38:22', '38:56',
       '32:14', '40:51', '33:31', '29:09', '39:49', '40:24', '36:30',
       '42:19', '39:43', '41:42', '39:25', '43:05', '39:06', '36:34',
       '38:57', '39:10', '43:49', '40:14', '38:03', '27:49', '38:18',
       '41:36', '39:18', '39:20', '38:32', '36:56', '27:09', '22:41',
       '46:39', '40:47', '42:21', '32:37', '42:14', '38:20', '36:27',
       '40:17', '35:17', '24:26', '44:44', '40:03', '35:60', '30:33',
       '27:58', '40:01', '39:22', '41:11', '34:53', '35:16', '31:27',
       '34:02', '42:15', '35:38', '39:53', '34:21', '41:33', '36:08',
       '33:52', '38:46', '45:05', '33:13', '39:26', '37:56', '35:42',
       '37:01', '28:52', '9:10', '38:10', '38:33', '41:13', '40:34',
       '32:00', '34:42', '38:08', '31:30', '43:48', '34:59', '39:03',
       '38:58', '41:22', '23:37', '39:37', '29:00', '34:45', '29:43',
       '30:44', '35:05', '38:50', '40:43', '35:18', '40:16', '37:32',
       '34:31', '26:11', '25:03', '33:58', '35:13', '38:44', '31:20',
       '23:31', '24:59', '23:04', '23:55', '36:52', '40:23', '26:35',
       '42:55', '31:52', '39:34', '36:46', '29:17', '29:53', '35:07',
       '40:39', '37:00', '42:26', '35:01', '42:22', '31:06', '41:44',
       '36:50', '33:03', '35:09', '46:13', '35:28', '28:25', '33:30',
       '33:42', '36:42', '50:03', '40:41', '31:18', '32:56', '36:18',
       '29:35', '30:18', '37:20', '40:07', '28:08', '34:49', '33:23',
       '36:21', '42:58', '28:23', '30:39', '33:40', '25:40', '19:51',
       '30:58', '39:45', '44:31', '24:07', '42:12', '34:09', '33:04',
       '28:59', '19:38', '26:27', '17:27', '15:14', '37:42', '26:04',
       '51:17', '32:39', '28:31', '34:03', '30:28', '31:17', '27:53',
       '27:16', '27:54', '29:59', '43:02', '35:08', '53:02', '37:06',
       '35:49', '34:48', '40:53', '34:29', '36:02', '30:20', '35:32',
       '42:20', '33:09', '33:15', '26:12', '28:44', '15:21', '29:41',
       '19:06', '29:54', '34:32', '36:57', '17:50', '23:36', '29:50',
       '31:35', '18:23', '25:23', '15:02', '47:55', '17:53', '32:24',
       '30:03', '27:10', '26:56', '17:15', '12:42', '25:53', '24:00',
       '24:39', '29:46', '31:23', '22:36', '26:44', '21:24', '28:04',
       '23:32', '43:07', '19:33', '21:19', '24:49', '32:48', '21:45',
       '21:40', '25:14', '22:55', '19:36', '21:56', '26:33', '25:46',
       '21:51', '20:25', '17:43', '27:30', '29:04', '24:17', '20:03',
       '26:13', '24:56', '33:08', '28:27', '28:49', '25:08', '25:21',
       '26:23', '25:42', '21:16', '22:18', '38:09', '11:42', '24:28',
       '13:34', '34:44', '22:59', '41:46', '23:51', '33:12', '9:59',
       '14:08', '19:35', '27:39', '15:26', '27:45', '13:25', '12:00',
       '15:10', '11:46', '19:27', '21:35', '16:57', '12:27', '4:43', '12',
       '27', '19', '14', '28', '29'], dtype=object)

In [322]:
minu = giannis['MIN']
minu = minu.str.replace(':', '.')
minu = minu.astype('float')
minu = round(minu)

In [323]:
giannis.MIN = minu
giannis.MIN.value_counts().sort_index()

0.0      1
4.0      1
9.0      1
10.0     2
11.0     3
12.0     5
13.0     2
14.0     2
15.0     7
16.0     1
17.0     5
18.0     3
19.0    10
20.0     5
21.0    11
22.0    10
23.0    13
24.0    17
25.0    18
26.0    32
27.0    23
28.0    27
29.0    30
30.0    41
31.0    34
32.0    40
33.0    43
34.0    52
35.0    67
36.0    49
37.0    38
38.0    34
39.0    41
40.0    26
41.0    19
42.0    15
43.0    10
44.0     3
45.0     4
46.0     2
48.0     1
50.0     2
51.0     1
53.0     1
Name: MIN, dtype: int64

In [324]:
giannis.dtypes

GAME_ID             int64
TEAM_ID             int64
TEAM_CITY          object
PLAYER_ID           int64
PLAYER_NAME        object
START_POSITION     object
MIN               float64
FGM               float64
FGA               float64
FG_PCT            float64
FG3M              float64
FG3A              float64
FG3_PCT           float64
FTM               float64
FTA               float64
FT_PCT            float64
OREB              float64
DREB              float64
REB               float64
AST               float64
STL               float64
BLK               float64
TO                float64
PF                float64
PTS               float64
PLUS_MINUS        float64
dtype: object

In [325]:
giannis.START_POSITION.value_counts()

F    648
G     28
C      1
Name: START_POSITION, dtype: int64

In [326]:
plusminusmean = giannis.PLUS_MINUS.mean()

In [327]:
giannis['START_POSITION']= giannis['START_POSITION'].replace(np.nan,'F')
giannis['PLUS_MINUS']= giannis['PLUS_MINUS'].replace(np.nan,plusminusmean)

In [328]:
missing = giannis[giannis.isnull().any(axis=1)]
missing

,GAME_ID,TEAM_ID,TEAM_CITY,PLAYER_ID,PLAYER_NAME,START_POSITION,MIN,FGM,FGA,FG_PCT,...,OREB,DREB,REB,AST,STL,BLK,TO,PF,PTS,PLUS_MINUS
17092,22100329,1610612749,Milwaukee,203507,Giannis Antetokounmpo,F,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3.065684
27188,12100026,1610612749,Milwaukee,203507,Giannis Antetokounmpo,F,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3.065684
27905,12100014,1610612749,Milwaukee,203507,Giannis Antetokounmpo,F,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3.065684
31250,22001068,1610612749,Milwaukee,203507,Giannis Antetokounmpo,F,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3.065684
41921,22000695,1610612749,Milwaukee,203507,Giannis Antetokounmpo,F,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3.065684
60440,12000043,1610612749,Milwaukee,203507,Giannis Antetokounmpo,F,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3.065684
64300,21901311,1610612749,Milwaukee,203507,Giannis Antetokounmpo,F,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3.065684
389566,11900051,1610612749,Milwaukee,203507,Giannis Antetokounmpo,F,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3.065684
393210,21801226,1610612749,Milwaukee,203507,Giannis Antetokounmpo,F,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3.065684
393960,21801193,1610612749,Milwaukee,203507,Giannis Antetokounmpo,F,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3.065684
395026,21801145,1610612749,Milwaukee,203507,Giannis Antetokounmpo,F,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3.065684
397109,21801065,1610612749,Milwaukee,203507,Giannis Antetokounmpo,F,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3.065684
397274,21801061,1610612749,Milwaukee,203507,Giannis Antetokounmpo,F,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3.065684
413930,21800395,1610612749,Milwaukee,203507,Giannis Antetokounmpo,F,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3.065684
424603,11800056,1610612749,Milwaukee,203507,Giannis Antetokounmpo,F,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3.065684
452685,21700264,1610612749,Milwaukee,203507,Giannis Antetokounmpo,F,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3.065684
461321,11700020,1610612749,Milwaukee,203507,Giannis Antetokounmpo,F,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3.065684
461770,11700009,1610612749,Milwaukee,203507,Giannis Antetokounmpo,F,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3.065684
464350,21601219,1610612749,Milwaukee,203507,Giannis Antetokounmpo,F,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3.065684
481023,21600562,1610612749,Milwaukee,203507,Giannis Antetokounmpo,F,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3.065684
522217,21500406,1610612749,Milwaukee,203507,Giannis Antetokounmpo,F,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3.065684
532364,21500012,1610612749,Milwaukee,203507,Giannis Antetokounmpo,F,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3.065684
539773,21401167,1610612749,Milwaukee,203507,Giannis Antetokounmpo,F,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3.065684
601362,21300222,1610612749,Milwaukee,203507,Giannis Antetokounmpo,F,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3.065684
602501,21300177,1610612749,Milwaukee,203507,Giannis Antetokounmpo,F,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3.065684
602771,21300167,1610612749,Milwaukee,203507,Giannis Antetokounmpo,F,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3.065684
604727,21300092,1610612749,Milwaukee,203507,Giannis Antetokounmpo,F,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3.065684
605370,21300066,1610612749,Milwaukee,203507,Giannis Antetokounmpo,F,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3.065684

In [337]:
giannis.loc[giannis.isnull().any(axis=1)].head()

Empty DataFrame
Columns: [GAME_ID, TEAM_ID, TEAM_CITY, PLAYER_ID, PLAYER_NAME, START_POSITION, MIN, FGM, FGA, FG_PCT, FG3M, FG3A, FG3_PCT, FTM, FTA, FT_PCT, OREB, DREB, REB, AST, STL, BLK, TO, PTS, PLUS_MINUS]
Index: []

[0 rows x 25 columns]

In [330]:
giannis.drop(giannis.loc[giannis.isnull().any(axis=1)].index, inplace=True)

In [331]:
giannis.isna().sum().sort_values(ascending=False)

GAME_ID           0
TEAM_ID           0
PTS               0
PF                0
TO                0
BLK               0
STL               0
AST               0
REB               0
DREB              0
OREB              0
FT_PCT            0
FTA               0
FTM               0
FG3_PCT           0
FG3A              0
FG3M              0
FG_PCT            0
FGA               0
FGM               0
MIN               0
START_POSITION    0
PLAYER_NAME       0
PLAYER_ID         0
TEAM_CITY         0
PLUS_MINUS        0
dtype: int64

In [332]:
giannis.dtypes

GAME_ID             int64
TEAM_ID             int64
TEAM_CITY          object
PLAYER_ID           int64
PLAYER_NAME        object
START_POSITION     object
MIN               float64
FGM               float64
FGA               float64
FG_PCT            float64
FG3M              float64
FG3A              float64
FG3_PCT           float64
FTM               float64
FTA               float64
FT_PCT            float64
OREB              float64
DREB              float64
REB               float64
AST               float64
STL               float64
BLK               float64
TO                float64
PF                float64
PTS               float64
PLUS_MINUS        float64
dtype: object

In [333]:
giannis = giannis.drop(['PF'], axis=1)

In [334]:
giannis.to_csv(r"C:\Users\kyrie\ironhack-Final-Project\final_project\giannis.csv")

In [335]:
giannis.columns

Index(['GAME_ID', 'TEAM_ID', 'TEAM_CITY', 'PLAYER_ID', 'PLAYER_NAME',
       'START_POSITION', 'MIN', 'FGM', 'FGA', 'FG_PCT', 'FG3M', 'FG3A',
       'FG3_PCT', 'FTM', 'FTA', 'FT_PCT', 'OREB', 'DREB', 'REB', 'AST', 'STL',
       'BLK', 'TO', 'PTS', 'PLUS_MINUS'],
      dtype='object')